### ISSUE TITLE
Suggestion: add support for GameCube sarcs like those used in Animal Crosing

### ISSUE THREAD

**Issue by mariomadproductions** [aboood40091/SARCExtract#1]
Suggestion: add support for GameCube sarcs like those used in Animal Crosing

**Comment by aboood40091** [comment]
Could you send some samples?

**Comment by mariomadproductions** [comment]
Yes:
https://drive.google.com/file/d/10UdgclzGcSfJ7yMLqyOY-_CvzMYnEseW/view?usp=sharing

**Comment by aboood40091** [comment]
Oh. Those are GameCube RARCs. This tool is for 3DS/WiiU/Switch SARC (sead archive).

**Comment by aboood40091** [comment]
There are some RARC tools online.
